spring:
  application:
    name: HotelService
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082


