spring:
  application:
    name: UserServices
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: aftab@14581


  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
